# Константи для парсингу вхідного файлу
STATE_DELIMITER = "STATES:"
INPUT_DELIMITER = "INPUTS:"
OUTPUT_DELIMITER = "OUTPUTS:"
START_STATE_DELIMITER = "START_STATE:"
TRANSITIONS_DELIMITER = "TRANSITIONS:"

KLEENE_STAR = '*'
CONCAT_SYMBOL = '.'
UNION_SYMBOL = '|'